spec-version:       0.36.0
name:               stack-hoogle
version:            0.5
license:            BSD3
github:             karamellpelle/stack-hoogle
license-file:       LICENSE
category:           Development
#author:             Neil Mitchell <ndmitchell@gmail.com>
#maintainer:         Neil Mitchell <ndmitchell@gmail.com>
#copyright:          Neil Mitchell 2004-2024
synopsis:           Haskell API Search (filtering by stack dependencies, i.e. package.yaml files)
description: >
  stack-hoogle is an expanded version of Hoogle (https://github.com/ndmitchell/hoogle) 
  that takes 'package.yaml' files into account.
#bug-reports:        https://github.com/ndmitchell/hoogle/issues
#tested-with:        GHC==9.8, GHC==9.6, GHC==9.4
extra-doc-files:
    - README.md
    - CHANGES.txt

#source-repository head
#    type:     git
#    location: https://github.com/ndmitchell/hoogle.git
dependencies:
    -  QuickCheck
    -  aeson >= 1.4.3.0
    -  base >= 4.9 && < 5
    -  blaze-html
    -  blaze-markup
    -  binary
    -  bytestring >= 0.10.2.0
    -  cmdargs
    -  conduit >= 1.3.0
    -  conduit-extra >= 1.2.3.2
    -  containers >= 0.5
    -  crypton-connection
    -  deepseq
    -  directory
    -  extra >= 1.6.6
    -  filepath
    -  foundation >= 0.0.13
    -  old-locale
    -  hashable
    -  haskell-src-exts >= 1.22 && < 1.24
    -  http-conduit >= 2.3
    -  http-types
    -  js-flot
    -  js-jquery
    -  mmap
    -  process-extras
    -  resourcet
    -  safe >= 0.3.20
    -  storable-tuple
    -  tar
    -  template-haskell
    -  text
    -  time >= 1.5
    -  transformers
    -  uniplate
    -  utf8-string
    -  vector
    -  wai
    -  wai-logger
    -  warp
    -  warp-tls
    -  zlib

internal-libraries:

    custom-hoogle:
        source-dirs  :  src-hoogle
        dependencies :  custom-hpack
        language     :  Haskell2010
        c-sources    :  cbits/text_search.c
        include-dirs :  cbits
        cc-options   :  -std=c99
        ghc-options  :  -fno-state-hack

        exposed-modules:
          - Hoogle
        generated-other-modules: 
          - Paths_stack_hoogle


executables:
    stack-hoogle:             
        main:               Main.hs
        language:           Haskell2010
        ghc-options:        -threaded

        dependencies:
            - base > 4 && < 5
            - custom-hoogle
