spec-version:       0.36.0
name:               stack-hoogle
version:            0.5
license:            BSD3
github:             karamellpelle/stack-hoogle
license-file:       LICENSE
category:           Development
#author:             Neil Mitchell <ndmitchell@gmail.com>
#maintainer:         Neil Mitchell <ndmitchell@gmail.com>
#copyright:          Neil Mitchell 2004-2024
synopsis:           Haskell API Search (filtering by stack dependencies, i.e. package.yaml files)
description: >
  stack-hoogle is an expanded version of Hoogle (https://github.com/ndmitchell/hoogle) 
  that takes 'package.yaml' files into account.
#bug-reports:        https://github.com/ndmitchell/hoogle/issues
#tested-with:        GHC==9.8, GHC==9.6, GHC==9.4
extra-doc-files:
    - README.md
    - CHANGES.txt

#source-repository head
#    type:     git
#    location: https://github.com/ndmitchell/hoogle.git

#dependencies:

internal-libraries:

    custom-hoogle:
        source-dirs  :  src-hoogle
        language     :  Haskell2010
        c-sources    :  cbits/text_search.c
        include-dirs :  cbits
        cc-options   :  -std=c99
        ghc-options  :  -fno-state-hack
        exposed-modules:
          - Hoogle
        generated-other-modules: 
          - Paths_stack_hoogle
        dependencies :  
          - QuickCheck
          - aeson 
          - base
          - blaze-html
          - blaze-markup
          - binary
          - bytestring 
          - cmdargs
          - conduit 
          - conduit-extra 
          - containers 
          - crypton-connection
          - deepseq
          - directory
          - extra 
          - filepath
          - foundation 
          - old-locale
          - hashable
          - haskell-src-exts 
          - http-conduit 
          - http-types
          - js-flot
          - js-jquery
          - mmap
          - process-extras
          - resourcet
          - safe 
          - storable-tuple
          - tar
          - template-haskell
          - text
          - time
          - transformers
          - uniplate
          - utf8-string
          - vector
          - wai
          - wai-logger
          - warp
          - warp-tls
          - zlib
          - hpack

executables:
    stack-hoogle:             
        main:               Main.hs
        language:           Haskell2010
        ghc-options:        -threaded

        dependencies:
            - base
            - custom-hoogle
